import Head from "next/head";
import Link from "next/link";

export default function Detail({ data }: any) {
  console.log(data);
  return (
    <>
      <Head>
        <title>✈️ Traveler&apos;s Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="grid place-content-center">
        <h1 className="mt-5">Current Country: {data.name?.common}</h1>
        <Link href={`/`}>
          <button>⬅️ Go Back</button>
        </Link>
      </section>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const res = await fetch(
    `https://restcountries.com/v3.1/name/${context.query.name}`
  );
  const [data] = await res.json();
  return { props: { data } };
}
