import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Detail() {
  const router = useRouter();
  const { name } = router.query;
  return (
    <>
      <Head>
        <title>✈️ Traveler&apos;s Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="grid place-content-center">
        <h1 className="mt-5">Current Country: {name}</h1>
        <Link href={`/`}>
          <button>⬅️ Go Back</button>
        </Link>
      </section>
    </>
  );
}
